import {StyleSheet, Dimensions} from 'react-native';

// FIXME: TODO: not sure this is the best solution to prevent cutoff on bottom
const screenHeight = Dimensions.get('window').height;
const screenWidth = Dimensions.get('window').width;

export const styles = StyleSheet.create({
  flexColContainer: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    // justifyContent: 'center',
    textAlign: 'center',
    position: 'relative',
    backgroundColor: '#30363a',
  },
  flexColContainerBtm: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    position: 'relative',
    backgroundColor: '#30363a',
    paddingBottom: 20,
  },
  blockFlexColContainer: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    // marginTop: 50,
    marginBottom: 50,
  },
  flexColContainerNoMargin: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    // marginTop: 50,
    marginBottom: 10,
  },
  flexFullCenter: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    // color: 'white',
    textAlign: 'center',
    position: 'relative',
    // height: 'full',
    backgroundColor: '#30363a',
    justifyContent: 'center',
  },
  infoText: {
    paddingHorizontal: 3,
    color: '#cec9c6',
    marginTop: 20,
  },
  button: {overflow: 'hidden', marginTop: 20, width: 100, borderRadius: 10},
  buttonTop: {overflow: 'hidden', borderRadius: 10},
  buttonBtm: {
    borderRadius: 10,
    marginBottom: 20,
    paddingBottom: 50,
    marginTop: 60,
    width: 100,
    overflow: 'hidden',
  },
  button2: {
    // marginTop: 20,
    // flex: 1,
    overflow: 'hidden',
    borderRadius: 10,
    position: 'absolute',
    top: 0,
    right: 0,
  },
  buttonInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    paddingBottom: 100,
    backgroundColor: '#30363a',
  },
  searchInput: {
    borderColor: '#cec9c6',
    borderWidth: 1,
    borderRadius: 10,
    height: 40,
    width: 300,
    marginTop: 10,
    // marginBottom: 20,
    backgroundColor: 'white',
    color: '#30363a',
  },
  foundUsersRow: {
    backgroundColor: 'white',
    paddingVertical: 15,
    borderBottomColor: '#cec9c6',
    borderBottomWidth: 2,
  },
  inputStyles: {
    borderColor: '#cec9c6',
    borderWidth: 1,
    borderRadius: 10,
    height: 40,
    width: 300,
    marginBottom: 25,
    backgroundColor: 'white',
    color: '#30363a',
  },
  bigLink: {
    fontSize: 20,
    marginTop: 15,
    color: '#318ce7',
  },
  recipeCard: {
    marginTop: 5,
    width: '60%',
    borderWidth: 1,
    borderColor: '#cec9c6',
    paddingHorizontal: 5,
    alignItems: 'center',
    textAlign: 'center',
    borderRadius: 10,
    backgroundColor: '#cfc9c5',
    // color: 'white',
  },
  recipeCardBtm: {
    marginTop: 5,
    borderWidth: 1,
    borderColor: '#cec9c6',
    paddingHorizontal: 5,
    alignItems: 'center',
    textAlign: 'center',
    borderRadius: 10,
    marginBottom: 30,
    // color: 'white',
  },
  userCard: {
    // flex: 1,
    borderColor: '#cec9c6',
    marginTop: 5,
    borderWidth: 1,
    paddingHorizontal: 30,
    paddingVertical: 20,
    borderRadius: 10,

    overflow: 'hidden',
    // position: 'relative',
    // width: screenWidth - 40,
  },
  recipeInfo: {flexDirection: 'row', marginBottom: 5},
  viewStyles: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textarea: {
    // height: 120,
    borderRadius: 10,
    color: '#30363a',
    textAlignVertical: 'top',
    width: 300,
    borderColor: '#555555',
    borderWidth: 1,
    backgroundColor: 'white',
  },
  linkStyle: {
    marginTop: 15,
    color: '#318ce7',
  },
  bottomLink: {
    marginTop: 15,
    color: '#318ce7',
    textAlign: 'center',
    fontSize: 20,
  },
  seperator: {height: 1, width: '100%', backgroundColor: '#000'},
  header: {
    fontSize: 32,
    marginVertical: 10,
    color: 'white',
  },
  inputStylesBottom: {
    borderColor: '#555555',
    borderWidth: 1,
    height: 40,
    borderRadius: 10,
    width: 300,
    marginBottom: 10,
    color: '#30363a',
    marginTop: 140,
  },
  groceryItem: {
    marginTop: 5,
    color: '#cec9c6',
    fontSize: 16,
  },
  noGroceryItemsText: {
    color: '#cec9c6',
    fontSize: 18,
  },
  kitchenParticipants: {
    color: '#cec9c6',
    textAlign: 'center',
    fontSize: 16,
  },
  scrollScreen: {
    // flex: 1,
    // width: screenWidth,
    height: screenHeight,
    // paddingBottom: 50,
    flexGrow: 1,
  },
});
